name: VoltskiyaDungeons
version: 1.0
main: com.voltskiya.structure.VoltskiyaPlugin
api-version: 1.19
authors: [ appleptr16 ]
softdepend: [ LoadDependencies, VoltPluginManager, AppleMCUtil, DecodingNms, VoltskiyaUtilities, VoltskiyaMobSystem ]
